In [0]:
import numpy as np

a = np.random.randn(5) # it will creates a random vector numbers

In [0]:
# a = a.reshape(5,1)

In [0]:
print(a)

[-0.76866781  1.04997366 -0.60984216  0.75399454 -0.55513562]


In [0]:
print(a.shape)

(5,)


In [0]:
print(a.T) # Transpose of "a" this returns rank 1 array

[-0.76866781  1.04997366 -0.60984216  0.75399454 -0.55513562]


In [0]:
print(np.dot(a,a.T)) #inner product between "a" and "a transpose"

2.9418856706724457


When You're coding a neural network you don't need to use a data structure like above. Instead use the following method.

In [0]:
a = np.random.randn(5,1) # this commits to a 5,1 column vector
print(a)

[[ 1.70146107]
 [ 0.8173017 ]
 [-0.41569615]
 [ 1.07876799]
 [ 0.83211314]]


In [0]:
print(a.T) # Now this return a 1 by 5 matrix

[[ 1.70146107  0.8173017  -0.41569615  1.07876799  0.83211314]]


In [0]:
print(np.dot(a,a.T)) # this gives you the outer product of a vector

[[ 2.89496976  1.39060702 -0.70729081  1.83548173  1.41580812]
 [ 1.39060702  0.66798207 -0.33974917  0.88167891  0.68008749]
 [-0.70729081 -0.33974917  0.17280329 -0.4484397  -0.34590623]
 [ 1.83548173  0.88167891 -0.4484397   1.16374037  0.89765702]
 [ 1.41580812  0.68008749 -0.34590623  0.89765702  0.69241228]]
