In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [0]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorization: " + str(1000*(toc-tic)) + "ms")

# non vectorized 

c = 0
tic = time.time()
for i in range(1000000):
  c += a[i]*b[i]
toc=time.time()  

print(c)
print("For Loop: " + str(1000*(toc - tic)) + "ms")

249403.89861202647
Vectorization: 2.2652149200439453ms
249403.89861203096
For Loop: 454.9686908721924ms


## Question 1
[Here is Question ](https://github.com/dayan2222/Neural-Network-Scripts/blob/master/question.PNG)

In [0]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [0]:
cal = A.sum(axis=0) # axis 0 will print the sum in row wise for x-axis we use axis = 1
print(cal)

[ 59.  239.  155.4  76.9]


In [0]:
percentage = 100 * A / cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
